apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-bio-cloud
  namespace: echo-bio
spec:
  selector:
    matchLabels:
      app: echo-bio-cloud
  template:
    metadata:
      labels:
        app: echo-bio-cloud
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
      - name: echo-bio-cloud
        image: airren/echo-bio-cloud:v0.0.8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
