apiVersion: v1
kind: Service
metadata:
  name: echo-bio-cloud
  namespace: echo-bio
spec:
  selector:
    app: echo-bio-cloud
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30086
  type: NodePort
  
